const INIT_PRODUCTS = 'INIT_PRODUCTS';
const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
const SET_PIZZA_BASIS = 'SET_PIZZA_BASIS';
const SET_PIZZA_PRODUCTS = 'SET_PIZZA_PRODUCTS';

export default {
    INIT_PRODUCTS,
    LOAD_PRODUCTS,
    SET_PIZZA_BASIS,
    SET_PIZZA_PRODUCTS
}
