const INIT_PRODUCTS = 'INIT_PRODUCTS';
const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
const SET_PIZZA_BASIS = 'SET_PIZZA_BASIS';
const SET_PIZZA_PRODUCTS = 'SET_PIZZA_PRODUCTS';
const REMOVE_PIZZA_PRODUCT = 'REMOVE_PIZZA_PRODUCT';
const INCREMENT_PRODUCT_COUNT = 'INCREMENT_PRODUCT_COUNT';
const DECREMENT_PRODUCT_COUNT = 'DECREMENT_PRODUCT_COUNT';

export default {
    INIT_PRODUCTS,
    LOAD_PRODUCTS,
    SET_PIZZA_BASIS,
    SET_PIZZA_PRODUCTS,
    REMOVE_PIZZA_PRODUCT,
    INCREMENT_PRODUCT_COUNT,
    DECREMENT_PRODUCT_COUNT
}
